### ISSUE TITLE
System.InvalidOperationException within DownloadDataTaskAsync

### ISSUE THREAD

**Issue by kevbite** [maximn/google-maps#43] opened 2015-10-21 10:18 UTC
Not really sure whats going off here, but i have a feelings its because the library is using an async void method without having a async context?
The `DownloadDataTaskAsync` method is currently using public `WebClient.DownloadDataAsync(Uri address)` and I'm guessing it just needs changing to use the one that returns a Task object - `WebClient.DownloadDataTaskAsync(Uri address)`

Details are below:

```
Exception thrown: 'System.InvalidOperationException' in GoogleMapsApi.dll

Additional information: An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.
```

Stack Trace:

```
   at System.Web.AspNetSynchronizationContext.OperationStarted()
   at System.Net.WebClient.DownloadDataAsync(Uri address, Object userToken)
   at System.Net.WebClient.DownloadDataAsync(Uri address)
   at GoogleMapsApi.WebClientExtensionMethods.DownloadDataTaskAsync(WebClient client, Uri address, TimeSpan timeout, CancellationToken token) in c:\code\google-maps\GoogleMapsApi\WebClientExtensionMethods.cs:line 119
   at GoogleMapsApi.Engine.MapsAPIGenericEngine`2.QueryGoogleAPIAsync(TRequest request, TimeSpan timeout, CancellationToken token) in c:\code\google-maps\GoogleMapsApi\Engine\MapsAPIGenericEngine.cs:line 120
   at GoogleMapsApi.EngineFacade`2.QueryAsync(TRequest request, CancellationToken token) in c:\code\google-maps\GoogleMapsApi\GoogleMaps.cs:line 215
```

**Comment by maximn** [comment] 2015-10-21 12:08
I'm not sure I'm following you on this one. It's just 2 different patterns void method and registering a handler *or* returning a Task.

Can you write a test that reproduces ?

**Comment by kevbite** [comment] 2015-10-21 14:00
I know the void methods also need to attach to the SynchronizationContext so that they can deal with exceptions being thrown from within a async void method, as a Task based method can just pass that along with a task and the consuming code can deal with the exception at anypoint.

Is there any reason why its using the void methods here? I've always tried to stick to these guidelines for async'ness - https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

**Comment by maximn** [comment] 2015-10-21 14:51
It's there for long time, can't remember now why or if there was a reason
to use one api over the other. You're welcome to issue a pull request if
you think it will help.

If you can, try to create a test to reproduce BEFORE you fix, then change
the API and verify that the test is fixed.

*-- Maxim.*

**Comment by kevbite** [comment] 2015-10-21 14:56
Yep no worries, Ill give it a go. At moment to get round the issue I've just called the none Async method.

**Comment by kevbite** [comment] 2015-11-07 13:22
Sorry took a while to get back, been extremely busy! I tried to write some failing tests but seems to work fine, I'm guessing its the SignalR environment that its running in which is weird because all the rest of the async calls we make work perfectly fine (Db/Api).

I have a feeling its something to do with the async void and that having to rely on a certain SynchronizationContext.

**Comment by maximn** [comment] 2015-11-07 19:53
What version of the .NET framework do you use? Maybe version mismatch of something you use?

**Comment by kevbite** [comment] 2015-11-07 21:22
It's targeting 4.5.1 but that shouldn't make any difference as the package is lower.

----- Reply message -----

**Comment by maximn** [comment] 2015-11-07 21:30
I've edited my response .. plz have a look agian


*-- Maxim.*

**Comment by kevbite** [comment] 2015-11-07 22:09
Sorry, replied back on my phone and it didn't give me an update version.

The page async stuff refers back to ASP.NET WebForms , we're calling it straight from SingalR Hub on top of owin.

I've push up an example of this to my github account - https://github.com/kevbite/GoogleMapsApi.Error

As you can see the Synchronous one works perfectly fine but the Asynchronous one throw the exception.

**Comment by maximn** [comment] 2015-11-07 22:49
As I don't have windows computer anymore so I can't really run your sample.

You can try to see if using the other Task API help in your sample and if
so issue a  pull request.

*-- Maxim.*

**Comment by kevbite** [comment] 2015-11-07 22:50
OK ill give it a go

**Comment by maximn** [comment] 2016-05-09 20:59
Hi, did u had a chance to check it?

**Comment by kevbite** [comment] 2016-05-09 21:05
Sorry been totally overwhelmed with work projects, so not had a chance to look at it.
Hi, did u had a chance to check it?

---

**Comment by maximn** [comment] 2016-05-09 21:42
As said before, I don't have windows anymore :(
Is this issue is still a problem for you? If not we can keep it open until one of us will find some more time to deal with that. Otherwise I'll try to find some one with Windows and Visual Studio installed.

**Comment by kevbite** [comment] 2016-05-09 21:45
I just ended up using the non task method, and lost the benefits of it being non io blocking as the system in which it was used the load is pretty low to notice any benefits.
As said before, I don't have windows anymore :(
Is this issue is still a problem for you? If not we can keep it open until one of us will find some more time to deal with that. Otherwise I'll try to find some one with Windows and Visual Studio installed.

---

**Comment by rhwilburn** [comment] 2017-07-08 05:03
I believe this is solved now from my change set here: https://github.com/maximn/google-maps/pull/99

This would have been because async behaves quite differently to how the self implemented task stuff was done previously in the library. Async has special behaviors for host systems like Owin or IIS where they help in terms of thread pooling and freeing up threads that are spin waiting (instead of it being dead, it likely serializes it to disk or memory, then frees that thread instead of occupying it and puts it back to the host pool (ie IIS or Owin); ie it reduces death by threads for apps in a similar way .net might serialize its memory to disk if it detects its not used. The methods are now async fully through which likely solves this issue. Can you please check and validate whether this can be closed out? @kevbite

**Comment by maximn** [comment] 2017-07-10 05:21
@kevbite I'm closing, let us know if need to reopen

**Closed by maximn** 2017-07-10 05:21 UTC
